"""initial schema

Revision ID: 94683330bd76
Revises: 
Create Date: 2026-09-10 22:15:03.123579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94683330bd76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension must exist before any `vector` column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_log_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_table('compliance_controls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('framework', sa.Text(), server_default='archlens-custom', nullable=False),
    sa.Column('control_code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework', 'control_code', name='uq_compliance_controls_framework_code')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.Text(), server_default='upload', nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('upload')", name='ck_documents_source_type'),
    sa.CheckConstraint("status IN ('pending','ingested','failed')", name='ck_documents_status'),
    sa.CheckConstraint('file_size_bytes >= 0', name='ck_documents_file_size_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_chunks_chunk_index_nonneg'),
    sa.CheckConstraint('length(text) > 0', name='ck_chunks_text_nonempty'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunks_document_chunk_index')
    )
    op.create_index('idx_chunks_content_hash', 'chunks', ['content_hash'], unique=False)
    op.create_index('idx_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('extraction_method', sa.Text(), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_method IN ('manual','llm_extracted')", name='ck_components_extraction_method'),
    sa.CheckConstraint("type IN ('service','datastore','queue','external_system','other')", name='ck_components_type'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_components_source_document_id', 'components', ['source_document_id'], unique=False)
    op.create_index('idx_components_tags', 'components', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_components_type', 'components', ['type'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('control_id', sa.UUID(), nullable=True),
    sa.Column('component_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','resolved','dismissed')", name='ck_findings_status'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_findings_confidence_range'),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_controls.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_findings_component_id', 'findings', ['component_id'], unique=False)
    op.create_index('idx_findings_control_id', 'findings', ['control_id'], unique=False)
    op.create_index('idx_findings_status', 'findings', ['status'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('relevance_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'chunk_id', name='uq_finding_evidence_finding_chunk')
    )
    op.create_index('idx_finding_evidence_chunk_id', 'finding_evidence', ['chunk_id'], unique=False)
    op.create_index('idx_finding_evidence_finding_id', 'finding_evidence', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_finding_evidence_finding_id', table_name='finding_evidence')
    op.drop_index('idx_finding_evidence_chunk_id', table_name='finding_evidence')
    op.drop_table('finding_evidence')
    op.drop_index('idx_findings_status', table_name='findings')
    op.drop_index('idx_findings_control_id', table_name='findings')
    op.drop_index('idx_findings_component_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index('idx_components_type', table_name='components')
    op.drop_index('idx_components_tags', table_name='components', postgresql_using='gin')
    op.drop_index('idx_components_source_document_id', table_name='components')
    op.drop_table('components')
    op.drop_index('idx_chunks_document_id', table_name='chunks')
    op.drop_index('idx_chunks_content_hash', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_content_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_table('compliance_controls')
    op.drop_index('idx_audit_log_event_type', table_name='audit_log')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS vector")
