"""phase 7 policy verdicts

Revision ID: 9fbf4e4d16c0
Revises: cc8e51c1a598
Create Date: 2026-09-11 12:29:43.233549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbf4e4d16c0'
down_revision: Union[str, Sequence[str], None] = 'cc8e51c1a598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('verdict', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('severity', sa.Text(), nullable=True))
    op.create_index('idx_findings_verdict', 'findings', ['verdict'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: CHECK constraints are not autodetected (same as
    # earlier migrations). Both nullable, so existing rows (all NULL)
    # already satisfy them — no backfill needed.
    op.create_check_constraint(
        "ck_findings_verdict", "findings", "verdict IS NULL OR verdict IN ('PASS','FAIL','UNKNOWN','CONFLICT')"
    )
    op.create_check_constraint(
        "ck_findings_severity",
        "findings",
        "severity IS NULL OR severity IN ('low','medium','high','critical')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_findings_severity", "findings", type_="check")
    op.drop_constraint("ck_findings_verdict", "findings", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_findings_verdict', table_name='findings')
    op.drop_column('findings', 'severity')
    op.drop_column('findings', 'verdict')
    # ### end Alembic commands ###
