"""phase 6 multimodal chunks

Revision ID: cc8e51c1a598
Revises: 540fcff68f20
Create Date: 2026-09-11 00:04:50.649863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc8e51c1a598'
down_revision: Union[str, Sequence[str], None] = '540fcff68f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('modality', sa.Text(), server_default='text', nullable=False))
    op.add_column('chunks', sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_chunks_modality', 'chunks', ['modality'], unique=False)
    # ### end Alembic commands ###

    # Hand-written: CHECK constraint text changes are not autodetected
    # (same as migrations 540fcff68f20 and e3034b9b35ac before it).
    op.create_check_constraint(
        "ck_chunks_modality", "chunks", "modality IN ('text','image_ocr','image_caption')"
    )
    op.drop_constraint("ck_components_extraction_method", "components", type_="check")
    op.create_check_constraint(
        "ck_components_extraction_method",
        "components",
        "extraction_method IN ('manual','llm_extracted','rule_based','vision_extracted')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_components_extraction_method", "components", type_="check")
    op.create_check_constraint(
        "ck_components_extraction_method",
        "components",
        "extraction_method IN ('manual','llm_extracted','rule_based')",
    )
    op.drop_constraint("ck_chunks_modality", "chunks", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_modality', table_name='chunks')
    op.drop_column('chunks', 'bbox')
    op.drop_column('chunks', 'modality')
    # ### end Alembic commands ###
